#############
#   BASIC   #
#############
name: Products
version: 0.1.0
description: Extraindo dados de teste de dummyjson.com

################
#   ENDPOINT   #
################
endpoint:
  uri: "https://dummyjson.com/products"
  method: GET
  response_format: JSON
  # headers:
    # Content-Type: application/json
  # body: 
    # param1: value1
    # param2: value2
  limit_extract: 1
  endpoint_config:
    timeout_in_seconds: 30
    query_params:
      - name: limit
        value: 10
      - name: skip 
        value: 0
    retry:
      attempts: 10 # Número de tentativas em caso de falha
      delay_in_seconds: 30 # Tempo de espera entre tentativas
    status_code_waiting:
      - 429 # Códigos de status HTTP que indicam que o cliente deve esperar antes de tentar novamente
    status_code_success:
      - 200 # Códigos de status HTTP que indicam sucesso
    status_code_skip:
      - 400 # Códigos de status HTTP que indicam que a resposta deve ser ignorada
    waiting_time_in_seconds: 60 # Tempo de espera em segundos quando um código de status de espera é recebido
    waiting_time_in_error_in_seconds: 30 # Tempo de espera em segundos quando um erro é recebido
    pagination:
      mode: offset
      location: query_param
      direction: next
      offset: $.skip
      limit: $.limit
      limit_value: 10

############
#   AUTH   #
############
auth:
  auth_mode: none

##############
#   TABLES   #
##############
tables:
  - name: products
    private_key_column_alias: id
    root: $.products
    columns_mode: defined # auto | defined
    columns:
      - path: id
        alias: id
        type: integer # string | integer | double | boolean | date | datetime | array
        format: "" # Usado quando type é 'date' ou 'datetime'
        # format pode ser "2006-01-02" para date ou "2006-01-02T15:04:05Z07:00" para datetime
      - path: title
        alias: title
        type: string # string | integer | double | boolean | date | datetime | array
        format: "" # Usado quando type é 'date' ou 'datetime'
      - path: description
        alias: description
        type: string # string | integer | double | boolean | date | datetime | array
        format: "" # Usado quando type é 'date' ou 'datetime'
      - path: price
        alias: price
        type: double # string | integer | double | boolean | date | datetime | array
        format: "" # Usado quando type é 'date' ou 'datetime'
      - path: price
        alias: price
        type: double # string | integer | double | boolean | date | datetime | array
        format: "" # Usado quando type é 'date' ou 'datetime'
