#############
#   BASIC   #
#############
version: 0.1.0
description: Extraindo dados de teste de dummyjson.com
url: https://dummyjson.com/products
_method: GET
# Por hora sรณ json
_response_format: JSON
_extraction_json_path: $
# #################
