#############
#   BASIC   #
#############
version: 0.1.0
description: Extraindo dados de teste de dummyjson.com
url: https://dummyjson.com/products
_method: GET
# RESPONSE #################
# Por hora só json
_response_format: JSON
_extraction_json_path: $
# OPÇÕES #################
_query_params:
  key1: env(HOME)
  key2: value2
_headers:
  header1: env(HOME)
  header2: value2
# BODY #################
_body:
  content_type: application/json # application/x-www-form-urlencoded | multipart/form-data | application/json | application/xml | application/graphql | application/protobuf | application/msgpack | application/cbor | application/x-ndjson | text/plain | text/csv | application/octet-stream
  # _file: "env(HOME)"
  _content: "{\"a\":\"b\"}"
  # _form_fields:
  #   username: "pedro"
  #   password: "123456"
  #   remember: "true"
  # _multi_part:
  #   fields:
  #     name1: value1
  #     name2: value2
  #   files:
  #     file1e2:
  #       - "path para o arquivo 1"
  #       - "path para o arquivo 2"
  #   file3:
  #       - "path para o arquivo 3"
